### ISSUE TITLE
Vertical bar mising (not broken one)

### ISSUE THREAD

**Issue by maciekpaprocki** [brajeshwar/entities#3]

**Comment by brajeshwar** [comment]
Do you mean ```|```? Can you show me an example?

**Comment by maciekpaprocki** [comment]
Yes. I couldn't find it.

**Comment by brajeshwar** [comment]
Ok. Can you go ahead and add it and send in a PR?

**Comment by rdlagemann** [comment]
Hi, can I add this one?

**Comment by brajeshwar** [comment]
Yes, please go ahead and send a PR.

**Comment by rdlagemann** [comment]
Ok, thanks. I will add other special characters of basic latin (vertical bar included), no problem?
