### ISSUE TITLE
No information is loading

### ISSUE THREAD

**Issue by stevenventimiglia** [brajeshwar/entities#8]
- The link provided produces a blank page.
 [https://brajeshwar.github.io/entities/](https://brajeshwar.github.io/entities/)

- A redirect to [http://brajeshwar.me/entities/](http://brajeshwar.me/entities/) may be the cause.

**Comment by brajeshwar** [comment]
Fixed. Github was re-directing all repositories pages through the primary domain that I tried using earlier. Removed that repo and now things are back to normalcy.
